InOutReg/urls.py
from django.urls import path

from .views import home_view, signup_view, dashboard_view

app_name = "InOutReg"

urlpatterns = [
    path('', home_view, name='home'),
    path('signup/', signup_view, name='sign-up'),
    path('dashboard/', dashboard_view, name='dashboard'),
]

Learning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('InOutReg.urls', namespace='users')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('pdf/', include('convert.urls'))
]

urlpatterns += [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

convert/urls.py
from django.urls import path

from .views import model_form_upload


urlpatterns = [
    path('', model_form_upload, name='file'),
]

profiles/urls.py
from django.urls import path, re_path

from .views import (
    signup, ProfileUpdateView, account_activation_sent_view, account_activate
)

app_name = 'profiles'

urlpatterns = [
    path('', signup, name='profile-signup'),
    path('<int:pk>/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

urlpatterns += [
    path('account-activation-sent/', account_activation_sent_view, name='account-activation-sent'),
    path('activate/<uidb64>/<token>/',
         account_activate, name='activate'),
]

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        label='',
        max_length=30,
        min_length=5,
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        )
    )

    email = forms.EmailField(
        label='',
        max_length=255,
        required=True,
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        )
    )

    password1 = forms.CharField(
        label='',
        max_length=30,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        )
    )

    password2 = forms.CharField(
        label='',
        max_length=30,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confirm Password",
                "class": "form-control"
            }
        )
    )

    location = forms.CharField(
        label='',
        max_length=30,
        required=False,
        widget=forms.HiddenInput(
            attrs={
                "display": "none"
            }
        )
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'location')

templates/app/dashboard.html
{% extends "base.html" %}

{% block title %}
	Dashboard
{% endblock %}

{% block content %}

	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-success mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}
<div class="container mt-4">
    <div class="row">

        <div class="col-md-2"></div>

        <div class="col-md-8 mt-7">

			<form class="text-center border border-secondary p-1" >

				<h1 class="mt-3 text-center">Welcome {{ request.user }}</h1>

			</form>
		</div>
	</div>
</div>

{% endblock content %}

templates/app/file_upload.html
{% extends "base.html" %}

{% block title %}
File-Upload
{% endblock %}

{% block content %}

<!-- Upload form. Note enctype attribute! -->

<div class="container mt-4">
    <div class="row">

        <div class="col-md-3"></div>

        <div class="col-md-6 mt-8">

            <h1 class="mt-6 text-center">Welcome {{ request.user }}</h1>

            <form class="text-center border border-secondary p-1" method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success" data-toggle="tooltip" data-placement="top"
                        title="Upload" type="submit">Upload</button>

            </form> <!-- <p><a href="{% url 'users:home' %}">Return to home</a></p> -->

        </div>
    </div>
</div>

<!-- List of uploaded documents -->
<p>
    <button class="btn btn-dark" type="button" data-toggle="collapse" data-target="#collapseExample"
            aria-expanded="false" aria-controls="collapseExample" data-toggle="tooltip" data-placement="top"
            title="List of Docs">
        Uploaded Files
    </button>
</p>
{% if documents %}
{% for doc in documents %}
<div class="collapse" id="collapseExample">
    <div class="row">
        <div class="col-sm-4">
            <div class="card">
                <a href="{{ doc.document.url}}">
                    <img class="card-img-top" src="{{ doc.document.url }}" alt="{{ doc.document }}">
                </a>
                <div class="card-body">
                    <h5 class="card-title">{{ doc.document }}</h5>
                    <p class="card-text">Here it is ur converted file press the below download button</p>
                    <a href="#" class="btn btn-primary" >Download</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<p>No documents.</p>
{% endif %}

{% endblock content %}

templates/app/home.html
{% extends "base.html" %}

{% block title %}
	Home
{% endblock %}

{% block content %}

	{{ block.super }}

{% endblock content %}

templates/app/profile_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
	Edit Bio
{% endblock %}

{% block content %}

	<div class="text-left mt-5 container">
		{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field|attr:"rows:20"|attr:"cols:20" }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
				<button type="submit">Submit</button>
		    </p>
		{% endfor %}
	</div>

{% endblock %}

templates/app/signup.html
{% extends "base.html" %}

{% block title %}
	Sign Up
{% endblock %}

{% block content %}
	
	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-danger mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

<div class="container mt-6">
<div class="row">
	<div class="col-md-1">
		
		<!--<div class="list-group mt-5">
		    <a href="{% url 'users:home' %}" class="list-group-item list-group-item-action waves-effect">Home</a>
			{% if profile %}
		    <a href="{% url 'profiles:profile-signup' %}" class="list-group-item bg-secondary text-white waves-effect">
		    		Profile Sign up
		    	{% else %}
		    	<a href="{% url 'users:sign-up' %}" class="list-group-item bg-secondary text-white waves-effect">
		    		Sign up
		    {% endif %}
		    </a>
		    <a href="{% url 'login' %}" class="list-group-item list-group-item-action waves-effect">Login</a>
		    <a href="{% url 'users:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Dashboard</a>
		    <a href="{% url 'users:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Profile</a>
		</div>-->

	</div>
<div class="col-md-2"></div>

        <div class="col-md-6 mt-2" align="center">

            <form method="post" class="text-center border border-secondary p-5" >
			{% csrf_token %}
		    <p class="h4 mb-4 text-secondary text-center">Sign up</p>

		    <!-- {{ form.as_p }} -->

			{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		    {% endfor %}

		    <!-- Sign up button -->
		    <button class="btn btn-secondary my-4 btn-block" type="submit">Sign up</button>

				<p>Already a member
                    <a href="{% url 'login' %}">Sign in</a>
                </p>

		    <!-- Social register -->
		    <p>or sign up with:</p>

		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-facebook"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-twitter"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-linkedin"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-github"></i>
		    </a>

		    <hr>

		    <!-- Terms of service -->
		    <p>By clicking
		        <em>Sign up</em> you agree to our
		        <a href="" target="_blank">terms of service</a>
		    </p>
		</form>
		<!-- Default form register -->
	</div>

	<div class="col-md-2"></div>

</div>
</div>

{% block script %}
<script type="text/javascript">
	function get_ip(json) {
		$("#id_location").val(json.ip);
	}
</script>

<script src="https://api.ipify.org?format=jsonp&callback=get_ip"></script>
{% endblock %}

{% endblock %}